config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  resources :recipes, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @recipes = Recipe.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def show
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(name: params[:recipe][:name],
                        recipe_type: params[:recipe][:recipe_type],
                        cuisine: params[:recipe][:cuisine],
                        ingredients: params[:recipe][:ingredients],
                        cook_method: params[:recipe][:cook_method],
                        cook_time: params[:recipe][:cook_time]
                      )

    if @recipe.save
      return redirect_to recipe_path(@recipe.id)
    end

    render :new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Livro de Receitas</h1>



<% @recipes.each do |recipe| %>

<!-- <a href="/receipes/<%= recipe.id %>" > <%= recipe.name %> </a>  -->

  <%= link_to recipe.name, recipe %>

<br />

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookbook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <ul>
        <li>
          <%= link_to 'Página inicial', root_path %>
        </li>
        <li>
          <%= link_to 'Cadastrar nova receita', new_recipe_path %>
        </li>
      </ul>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/recipes/new.html.erb
<%= form_with model: Recipe.new do |f| %>
  <%= f.label 'Nome: ' %>
  <%= f.text_field :name %> <br>

  <%= f.label 'Tipo de receita: ' %>
  <%= f.text_field :recipe_type %> <br>

  <%= f.label 'Culinária: ' %>
  <%= f.text_field :cuisine %> <br>

  <%= f.label 'Ingredientes: ' %>
  <%= f.text_area :ingredients %> <br>

  <%= f.label 'Modo de preparo: ' %>
  <%= f.text_field :cook_method %> <br>

  <%= f.label 'Tempo de preparo (min): ' %>
  <%= f.number_field :cook_time %> <br>

  <%= f.submit 'Salvar' %>

<% end %>

app/views/recipes/show.html.erb
<h1>Informações sobre a receita <%= @recipe.name %> </h1>


<dl>
  <dt>
    <strong>Nome: </strong><%= @recipe.name %>
  </dt>

  <dd>
    <strong>Tipo: </strong><%= @recipe.recipe_type %>
  </dd>

  <dd>
    <strong>Culinária: </strong><%= @recipe.cuisine %>
  </dd>

  <dd>
    <strong>Ingredientes: </strong><%= @recipe.ingredients %>
  </dd>

  <dd>
    <strong>Modo de preparo: </strong><%= @recipe.cook_method %>
  </dd>

  <dd>
    <strong>Tempo de preparo: </strong><%= @recipe.cook_time %>
  </dd>
</dl>